<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Incluir utilidades comunes y funciones matemáticas -->
  <xacro:include filename="$(find onrobot_description)/urdf/inc/common_utils.xacro" />
  <xacro:include filename="$(find xacro)/xacro/math.xacro" /> <!-- Proporciona M_PI, sin(), cos(), etc. -->

  <!-- Macro para OnRobot 3FG15 -->
  <xacro:macro name="onrobot_3fg15" params="prefix onrobot_type:='3fg15'">

    <!-- === CONSTANTES DEL GRIPPER === -->
    <xacro:property name="min_diameter" value="0.000" />  <!-- m -->
    <xacro:property name="max_diameter" value="0.150" />  <!-- m (150 mm) -->

    <!-- Ángulo total por dedo: 120° = 2π/3 rad -->
    <xacro:property name="total_angle" value="${2 * M_PI / 3}" />  <!-- 120° en radianes -->
    <xacro:property name="angle_per_meter" value="${total_angle / (max_diameter - min_diameter)}" />
    <xacro:property name="min_angle" value="${-M_PI / 3}" />      <!-- -60° -->
    <xacro:property name="max_angle" value="${ M_PI / 3}" />      <!-- +60° -->

    <!-- Offset para que en diámetro=0 → ángulo = -60° -->
    <xacro:property name="mimic_offset" value="${min_angle}" />

    <!-- === BASE LINK === -->
    <link name="${prefix}onrobot_base_link">
      <inertial>
        <origin xyz="0 0 0.04" rpy="0 0 0"/>
        <mass value="1.2"/>
        <inertia ixx="0.012" ixy="0.0" ixz="0.0" iyy="0.012" iyz="0.0" izz="0.008"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/visual/base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.04" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/collision/base.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <!-- === DEDOS === -->
    <!-- Left Finger -->
    <link name="${prefix}left_finger_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.08"/>
        <inertia ixx="0.00008" ixy="0.0" ixz="0.0" iyy="0.00008" iyz="0.0" izz="0.00008"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/visual/left_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/collision/left_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <!-- Right Finger -->
    <link name="${prefix}right_finger_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.08"/>
        <inertia ixx="0.00008" ixy="0.0" ixz="0.0" iyy="0.00008" iyz="0.0" izz="0.00008"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/visual/right_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/collision/right_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <!-- Middle Finger -->
    <link name="${prefix}middle_finger_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.08"/>
        <inertia ixx="0.00008" ixy="0.0" ixz="0.0" iyy="0.00008" iyz="0.0" izz="0.00008"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/visual/middle_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://onrobot_description/meshes/3fg15/collision/middle_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <!-- Dummy link para control de ancho -->
    <link name="${prefix}finger_width_mock_link"/>

    <!-- === JOINT PRINCIPAL (controlado por el driver) === -->
    <joint name="${prefix}finger_diameter" type="prismatic">
      <parent link="${prefix}onrobot_base_link"/>
      <child link="${prefix}finger_width_mock_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${min_diameter}" upper="${max_diameter}" effort="200" velocity="0.5"/>
    </joint>

    <!-- === DEDOS: REVOLUTE + MIMIC === -->

    <!-- Left Finger (rotado 180°) -->
    <joint name="${prefix}left_finger_joint" type="revolute">
      <parent link="${prefix}onrobot_base_link"/>
      <child link="${prefix}left_finger_link"/>
      <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>   <!-- 180° -->
      <axis xyz="0 0 1"/>
      <limit lower="${min_angle}" upper="${max_angle}" effort="200" velocity="0.5"/>
      <mimic joint="${prefix}finger_diameter" multiplier="${angle_per_meter}" offset="${mimic_offset}"/>
    </joint>

    <!-- Right Finger (0°) -->
    <joint name="${prefix}right_finger_joint" type="revolute">
      <parent link="${prefix}onrobot_base_link"/>
      <child link="${prefix}right_finger_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${min_angle}" upper="${max_angle}" effort="200" velocity="0.5"/>
      <mimic joint="${prefix}finger_diameter" multiplier="${angle_per_meter}" offset="${mimic_offset}"/>
    </joint>

    <!-- Middle Finger (120°) -->
    <joint name="${prefix}middle_finger_joint" type="revolute">
      <parent link="${prefix}onrobot_base_link"/>
      <child link="${prefix}middle_finger_link"/>
      <origin xyz="0 0 0" rpy="${2 * M_PI / 3} 0 0"/>  <!-- 120° -->
      <axis xyz="0 0 1"/>
      <limit lower="${min_angle}" upper="${max_angle}" effort="200" velocity="0.5"/>
      <mimic joint="${prefix}finger_diameter" multiplier="${angle_per_meter}" offset="${mimic_offset}"/>
    </joint>

    <!-- === TCP (Tool Center Point) === -->
    <link name="${prefix}gripper_tcp"/>
    <joint name="${prefix}tcp_joint" type="fixed">
      <parent link="${prefix}onrobot_base_link"/>
      <child link="${prefix}gripper_tcp"/>
      <origin xyz="0 0 0.13" rpy="0 0 0"/>  <!-- 130 mm hacia adelante -->
    </joint>

    <!-- === TRANSMISSION (para ROS Control) === -->
    <xacro:transmission_macro prefix="${prefix}" joint_name="finger_diameter"/>

  </xacro:macro>
</robot>